// with argument and with return type

#include<stdio.h>
#include<conio.h>
int get(int a,int b)
{
	//clrscr();
	int C;

	C=a+b;
	return C;
       /*	printf("the addition is=%d",a+b);
	printf("\nthe subtraction is=%d",a-b);
	printf("\nthe multiplication is=%d",a*b);
	printf("\nthe division is=%d",a/b);  */
}
void main()
{
	int a=10,b=20,C;

     //	sum(100,20);
	printf("\n sum=%d",C);
	getch();
}